version: '3'
services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    environment:
      - ENV_VARIABLE=value
    deploy:
      resources:
        limits:
          cpus: '4.0'  
          memory: 8G   
        reservations:
          cpus: '4.0'  
          memory: 4G  